services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chatops-backend
    ports:
      - "8000:8000"
    environment:
      APP_NAME: "ChatOps AI Platform API"
      APP_VERSION: "1.0.0"
      ENVIRONMENT: "dev"
      API_PREFIX: "/api"
    networks:
      - chatops-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chatops-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_BASE_URL: "http://18.222.112.51:8000"
    depends_on:
      - backend
    networks:
      - chatops-network

networks:
  chatops-network:
    driver: bridge
